linters:
  enable-all: true
  disable:
    # deprecated:
    - golint
    - interfacer
    - maligned
    - scopelint

    # godox doesn't allow TODO in comments
    - godox

    # exhaustivestruct requires that all constructed structs include all values, even if one value is the db id for a new object
    - exhaustivestruct

  fast: false
