linters:
  enable-all: true
  disable:
    # deprecated:
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint

    # gci - giving cryptic errors
    - gci

    # godox doesn't allow TODO in comments
    - godox

    # dupl doesn't correctly detect duplicate lines
    - dupl

    # exhaustruct and exhaustivestruct require that all constructed structs include all values, even if one value is the db id for a new object
    - exhaustruct
    - exhaustivestruct

  fast: false

linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-numbers: 2,3
